name: CI Pipeline

on:
  push:
    branches:
      - main  # Déclenche l'action sur des pushs vers la branche principale
  pull_request:
    branches:
      - main  # Déclenche l'action lors de la création d'une pull request vers la branche principale

jobs:
  install:
    runs-on: ubuntu-latest  # Utilisation d'une machine virtuelle Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupère le code du repository

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Configure Node.js
        with:
          node-version: '16'  # Choix de la version de Node.js (peut être ajusté si nécessaire)

      - name: Install dependencies
        run: npm install  # Installe les dépendances depuis le fichier package.json

  validate:
    runs-on: ubuntu-latest  # Utilisation de la machine virtuelle Ubuntu pour l'étape de validation
    needs: install  # L'étape "validate" attend la fin de l'étape "install"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupère de nouveau le code du repository pour l'étape suivante

      - name: Lint code (ESLint)
        run: npm run lint  # Exécute la commande "npm run lint" définie dans package.json, qui appelle ESLint
